accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"
urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
]

comento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("home.urls")),
    path("galaxy/", include("galaxy.urls")),
    path("shop/", include("shop.urls")),
    path("accounts/", include("accounts.urls")),
    path("mysite/", include("mysite.urls")),
    path("pages/", include("pages.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

galaxy/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("<id>/", views.index, name="index"),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

mysite/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index),
    path("<int:content_id>/", views.detail, name="detail"),
    path(
        "comment/create/<int:content_id>/", views.comment_create, name="comment_create"
    ),
    path(
        "comment/update/<int:comment_id>/", views.comment_update, name="comment_update"
    ),
    path(
        "comment/delete/<int:comment_id>/", views.comment_delete, name="comment_delete"
    ),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.mainpage),
    path("company/", views.company),
]

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

accounts/models.py
from django.db import models

# Create your models here.

mysite/models.py
from django.db import models
from django.contrib.auth.models import User


class MainContent(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content_list = models.ForeignKey(MainContent, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

mysite/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from accounts.forms import SignupForm


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/")
    else:
        form = SignupForm()

    return render(request, "accounts/signup.html", {"form": form})

galaxy/views.py
from django.shortcuts import render


def index(request, id):
    return render(request, "galaxy/galaxy-s23-ultra.html")

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, "home/index.html")

mysite/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .models import MainContent, Comment
from .forms import CommentForm


@login_required(login_url="accounts:login")
def comment_update(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        raise PermissionDenied
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect("detail", content_id=comment.content_list.id)
    else:
        form = CommentForm(instance=comment)
    context = {"comment": comment, "form": form}
    return render(request, "mysite/comment_form.html", context)


@login_required(login_url="accounts:login")
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        raise PermissionDenied
    else:
        comment.delete()
    return redirect("detail", content_id=comment.content_list.id)


def index(request):
    content_list = MainContent.objects.order_by("-pub_date")
    context = {"content_list": content_list}
    return render(request, "mysite/content_list.html", context)


def detail(request, content_id):
    content_list = get_object_or_404(MainContent, pk=content_id)
    context = {"content_list": content_list}
    return render(request, "mysite/content_detail.html", context)


@login_required(login_url="accounts:login")
def comment_create(request, content_id):
    content_list = get_object_or_404(MainContent, pk=content_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.content_list = content_list
            comment.author = request.user
            comment.save()
            return redirect("detail", content_id=content_list.id)
    else:
        form = CommentForm()
    context = {"content_list": content_list, "form": form}
    return render(request, "mysite/content_detail.html", context)

pages/views.py
from django.shortcuts import render


def mainpage(request):
    return render(request, "pages/mainpage.html")


def company(request):
    return render(request, "pages/company_info.html")

shop/views.py
from django.shortcuts import render


def index(request):
    return render(request, "shop/index.html")

templates/_base.html
<!-- templates/_base.html -->
{% load static tailwind_tags %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% tailwind_css %}

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GALAXY</title>
    <link rel="stylesheet" href="{% static 'css/output.css' %}" />
    <nav class="bg-zinc-900 mb-10 p-4 text-white">
      <ul class="flex justify-end p-4">
        <li class="mr-4"><a class="nav-link" href="/">Home</a></li>
        <li class="mr-4">
          <a class="nav-link" href="/pages/company/">Company Info</a>
        </li>
        <li class="mr-4">
          <a class="nav-link" href="/mysite/">Product</a>
        </li>
        {% if user.is_authenticated %}
        <li class="mr-4">
          <a
            class="nav-link"
            href="{% url
      'accounts:logout' %}"
            >{{ user.username }} (logout)</a
          >
        </li>
        {% else %}
        <li class="mr-4">
          <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </head>
  <body class="w-full h-full">
    {% block content %} {% endblock content %}

    <div></div>

    <div class="h-fit bg-zinc-900 text-gray-500 p-10 mt-10">
      <div class="ml-10">
        <div class="mb-4">
          *All images provided on this page are Samsung Electronics images
          unless otherwise noted. All rights to the images belong to Samsung
          Electronics.
        </div>
        <div class="mb-4">
          *Snapdragon is a product of Qualcomm Technologies, Inc. and/or its
          subsidiaries.
        </div>
        <div class="mb-4">
          *Snapdragon is a trademark or registered trademark of Qualcomm
          Incorporated.
        </div>
      </div>
    </div>
  </body>
</html>

templates/accounts/login.html
{% extends "_base.html" %} {% block content %} {% if form.errors %}
<p>아이디 또는 비밀번호가 틀립니다. 다시 시도해주세요.</p>
{% endif %}
<form method="post" action="{% url 'accounts:login' %}">
  {% csrf_token %}
  <table>
    <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
    </tr>
    <tr>
      <td>{{ form.password.label_tag }}</td>
      <td>{{ form.password }}</td>
    </tr>
  </table>
  <input type="submit" value="login" />
</form>
<a href="{% url 'accounts:signup' %}">signup</a>
{% endblock %}

templates/accounts/signup.html
{% extends "_base.html" %} {% block content %}
<h2 class="m-4">Sign up</h2>
<form method="post" class="m-4">
  {% csrf_token %}
  <p class="m-4">{{ form.as_p }}</p>
  <button class="rounded-lg border-gray border-2 mt-4" type="submit">
    Sign up
  </button>
</form>
{% endblock %}

templates/galaxy/galaxy-s23-ultra.html
<!-- templates/home/index.html -->
{% extends "../_base.html" %} {% block content %}
<nav class="bg-gray-100 fixed w-full z-10 top-0 left-0">
  <div
    class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <div class="flex self-center text-2xl font-semibold whitespace-nowrap">
      Galaxy S23 Ultra
    </div>

    <div class="flex items-center justify-between hidden md:flex w-auto">
      <ul class="flex flex-col p-4 md:p-0 mt-4 md:flex-row md:space-x-8 mt-0">
        <li>
          <span class="block py-2 pr-2 text-gray-500">Overview</span>
        </li>
        <li>
          <a href="#" class="block py-2 pr-2 text-black">Tech Specs</a>
        </li>
        <li>
          <a href="#" class="block py-2 text-black">
            <div
              class="rounded-xl bg-blue-600 hover:bg-sky-600 px-4 text-white"
              id="title-galaxy-s23-ultra-buy">
              Buy
            </div></a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="block bg-black">
  <div class="relative w-screen h-fit items-center">
    <img
      class="pt-20"
      src="/static/image/galaxy-s23-ultra/galaxy-s23-ultra.png" />
    <div
      class="absolute inset-y-0 my-auto flex flex-col h-fit justify-between items-center p-20 left-20">
      <div class="mt-40">
        <div class="text-3xl text-center font-semibold" style="color: #878d81">
          Galaxy S23 Ultra
        </div>
        <div class="mt-2 text-lg text-white">
          From $1199 or $49.95/mo. for 24 mo.
        </div>
        <a href="/shop/"
          ><div
            class="mx-28 mt-8 text-lg rounded-xl bg-blue-600 hover:bg-sky-600 px-4 text-white text-center">
            Buy
          </div>
        </a>
      </div>
    </div>
  </div>

  <div class="relative w-full h-fit bg-zinc-900" id="highlights">
    <div class="w-3/5 mx-auto">
      <div class="mb-8 pt-60 flex justify-between items-end">
        <div class="p-4 text-gray-500 text-6xl font-semibold">
          Get the highlights.
        </div>
        <div class="flex flex-row">
          <div class="p-4 text-blue-500 font-medium">Watch the film ></div>
          <div class="p-4 text-blue-500 font-medium">Watch the event ></div>
        </div>
      </div>
    </div>

    <div class="mx-auto w-3/5 h-fit pb-32">
      <div class="w-5/6 h-fit p-14 mx-auto bg-black rounded-xl text-white">
        <div class="text-2xl font-semibold">
          World’s fastest <br />
          Snapdragon
        </div>

        <img
          class="mx-auto items-center"
          src="/static/image/galaxy-s23-ultra/qualcomm-snapdragon-8.png" />
      </div>
    </div>
  </div>
  <div class="relative w-full h-fit p-16" id="ap">
    <div
      class="w-5/6 mx-auto mb-20 text-white text-center text-5xl font-semibold">
      Power for <br />those who don't pause
    </div>

    <img
      class="w-3/5 mx-auto items-center"
      src="/static/image/galaxy-s23-ultra/galaxy-s23-ultra-highlights-performance-end.webp" />

    <div class="w-3/5 mx-auto mt-10 flex flex-col">
      <div class="w-3/5 text-gray-500 ml-20 text-lg font-semibold">
        Game at full throttle and smoothly switch between apps with our
        <span class="text-white">fastest processor ever.</span>
      </div>
      <div
        class="w-3/4 mt-20 ml-20 text-white flex flex-col text-xs text-gray-700">
        <div class="mb-4">
          *Wreckfest available for purchase and download in the Samsung Galaxy
          Store app. Content is generally suitable for ages 13 and up. May
          contain violence, suggestive themes, crude humor, minimal blood,
          simulated gambling and/or infrequent use of strong language. Wreckfest
          ©2022 THQ Nordic AB, Sweden. Wreckfest is a registered trademark of
          THQ Nordic AB, Sweden. All rights reserved. All other trademarks,
          logos, and copyrights are property of their respective owners.
        </div>
        <div>
          *Image simulated for illustrative purposes. Actual UI may be
          different.
        </div>
      </div>
    </div>
  </div>
  <div class="relative w-full h-fit p-16 bg-zinc-900" id="camera">
    <div class="w-3/5 mx-auto mb-20 text-white text-5xl font-semibold">
      Outstanding specifications that everyone will envy
      <div class="w-2/3 mt-10 text-gray-500 text-lg font-semibold">
        Take crisp photos and videos, no matter the lighting. Galaxy's most
        advanced camera sensor and fastest processor reduce noise in low light
        for stunning shots.
      </div>
    </div>
    <img
      class="w-3/5 mx-auto items-center"
      src="/static/image/galaxy-s23-ultra/galaxy-s23-ultra-highlights-nightography.avif" />
    <div class="h-screen flex flex-col justify-between mt-20">
      <div class="w-3/5 mx-auto mt-20 flex flex-row pl-10">
        <img
          class="w-3/5 mx-auto items-center"
          src="/static/image/galaxy-s23-ultra/galaxy-s23-ultra-highlights-nightgraphy-portrait-02.jpg" />
        <div class="flex flex-col pl-10 justify-center">
          <div class="text-white text-xl mb-8">NIGHT PORTRAIT</div>
          <div class="w-3/4 text-gray-500">
            This camera delivers on depth and dimension. Gently blur the
            background to put your friends in focus and let incredible details
            shine.
          </div>
        </div>
      </div>
      <div class="w-3/5 mx-auto mt-20 flex flex-row pl-10">
        <div class="flex flex-col pr-10 justify-center">
          <div class="text-white text-xl mb-8">ASTRO HYPERLAPSE</div>
          <div class="w-3/4 text-gray-500">
            Transform a starry sky into a work of art. Turn on Hyperlapse to
            record timelapses with bright clarity, speeding up minutes of
            footage into stunning seconds.
          </div>
        </div>
        <img
          class="w-3/5 mx-auto items-center"
          src="/static/image/galaxy-s23-ultra/galaxy-s23-ultra-highlights-nightgraphy-astro-end.jpg" />
      </div>
    </div>
    <div
      class="w-3/5 mx-auto mt-40 mb-20 text-white text-5xl font-semibold text-center">
      200MP wow-worthy resolution
    </div>
    <div class="flex justify-center h-1/2">
      <img
        class="w-3/5 mx-auto items-center"
        src="/static/image/galaxy-s23-ultra/gsmarena_204.jpg" />
    </div>
  </div>

  <div class="relative w-full h-screen p-16" id="spen">
    <div class="w-3/5 mt-40 mx-auto">
      <div class="w-1/2 mb-20 text-white text-5xl font-semibold">
        Note's signature tool comes built in
      </div>
      <div class="flex flex-row">
        <div class="w-1/3 text-gray-500 text-lg font-semibold pr-20">
          S Pen keeps the legacy of Galaxy Note alive. Capture scribbles,
          strokes of genius and
          <span class="text-white"
            >everything in between with the built-in S Pen.</span
          >
          You can even use it to snap pics without needing to set a selfie
          timer.
        </div>
        <img
          class="w-1/2 mx-auto items-center"
          src="/static/image/galaxy-s23-ultra/galaxy-s23-ultra-highlights-spen.jpg" />
      </div>
    </div>
  </div>

  <div class="relative w-full h-fit p-16 bg-zinc-900" id="battery">
    <div class="flex flex-col w-3/5 mx-auto">
      <div class="mb-10 text-center text-white text-5xl font-semibold">
        Bring on the boss battles
      </div>
      <div class="text-gray-500 text-lg text-center font-semibold">
        This intelligent 5000mAh battery saves power for go time, <br />so you
        can
        <span class="text-white">game and stream into the night.</span>
      </div>

      <img
        class="w-1/2 mx-auto mb-10"
        src="/static/image/galaxy-s23-ultra/galaxy-s23-ultra-highlights-battery-s.png" />
      <div class="flex flex-row text-gray-500 justify-between mx-auto">
        <div class="w-1/2 flex flex-col text-gray-500 text-lg font-semibold">
          <div class="mb-10">
            <div class="mb-4">Up to</div>
            <div class="text-white text-5xl font-semibold mb-4">20 hrs</div>
            <div>video playback on <br />Galaxy S23 Ultra</div>
          </div>
          <div>
            <div class="mb-4">Up to</div>
            <div class="text-white text-5xl font-semibold mb-4">37 mins</div>
            <div>charge to 80%</div>
          </div>
        </div>
        <div class="ml-10 pt-4 px-10 text-lg">
          <div class="mb-8">
            Add a Fast Wireless Charging 2.0 Charger for
            <span class="text-white"> fast, efficient wireless charging</span>
          </div>
          <div class="border-t-2 border-gray-500 mb-8"></div>
          <div class="">
            <div class="mb-4">
              Galaxy S23 Ultra has up to 9 more hours video playback than Galaxy
              S20 Ultra
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="relative w-full h-fit p-16" id="display">
    <div class="flex flex-col w-3/5 mx-auto">
      <div class="mb-10 text-center text-white text-5xl font-semibold">
        A bright future in sight
      </div>

      <img
        class="mx-auto items-center mb-20"
        src="/static/image/galaxy-s23-ultra/galaxy-s23-ultra-highlights-display.jpg" />
      <div
        class="w-1/2 mx-auto text-gray-500 text-lg text-center font-semibold">
        Dynamic AMOLED 2X delivers clear, colorful details on screen, whether
        dimmed low or on full brightness.
        <span class="text-white">120Hz technology intelligently optimizes</span>
        the refresh rate to smooth out action and save on battery.
      </div>
    </div>
  </div>

  <div class="relative w-full h-fit p-16" id="other">
    <div class="w-3/5 h-fit mb-28 bg-zinc-900 mx-auto py-20" id="oneui">
      <div class="flex flex-col w-3/5 mx-auto">
        <div class="mb-20 text-white text-5xl font-semibold">
          Your Galaxy, the way you like it
        </div>

        <img
          class="mx-auto items-center mb-20"
          src="/static/image/galaxy-s23-ultra/galaxy-s23-ultra-highlights-one-ui.png" />
        <div class="text-gray-500 text-lg font-semibold">
          Now it's easier than ever to set your phone up just for you. One UI
          maximizes customization, allowing you to pick almost every detail,
          including video lockscreens and custom widgets.
        </div>
      </div>
    </div>
    <div class="w-3/5 h-fit mb-28 bg-zinc-900 mx-auto py-20" id="pcContinuity">
      <div class="flex flex-col w-3/5 mx-auto">
        <div class="mb-20 text-white text-5xl font-semibold">
          Multi Control makes multitasking easier
        </div>

        <img
          class="mx-auto items-center mb-20"
          src="/static/image/galaxy-s23-ultra/galaxy-s23-ultra-highlights-pc-continuity.png" />
        <div class="text-gray-500 text-lg font-semibold">
          When the ideas are flowing, sync your phone and PC for a 2-for-1
          experience. Without switching your mouse, keyboard or touchpad, you
          can drag and drop, copy and paste and type on both devices for your
          most efficient screentime yet.
        </div>
      </div>
    </div>
    <div class="w-3/5 h-fit mb-28 bg-zinc-900 mx-auto py-20" id="environment">
      <div class="flex flex-col w-3/5 mx-auto">
        <div class="mb-20 text-white text-5xl font-semibold">
          Designed with our planet in mind
        </div>

        <img
          class="w-full mx-auto items-center mb-20"
          src="/static/image/galaxy-s23-ultra/galaxy-s23-ultra-env.jpeg" />

        <div class="text-gray-500 text-lg font-semibold">
          Crafted in part with recycled glass and ocean-bound plastic, each
          phone comes in a recycled paper box.
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}
</div>

templates/galaxy/index.html
<!-- templates/home/index.html -->
{% extends "../_base.html" %} {% block content %}
<style>
  #galaxy-s23-ultra,
  #galaxy-s23-plus,
  #galaxy-s23 {
    display: none;
  }
</style>

<script>
  function getCurrentURL() {
    return window.location.pathname;
  }
  function showDivBasedOnURL() {
    var currentURL = getCurrentURL();
    if (currentURL === "/galaxy/s23-ultra/") {
      document.getElementById("galaxy-s23-ultra").style.display = "block";
    } else if (currentURL === "/galaxy/s23-plus/") {
      document.getElementById("galaxy-s23-plus").style.display = "block";
    } else if (currentURL === "/galaxy/s23/") {
      document.getElementById("s23").style.display = "block";
    }
  }
  window.onload = showDivBasedOnURL;
</script>

<div></div>
<div class="" id="galaxy-s23-ultra">test galaxy s23 ultra</div>
<div class="" id="galaxy-s23-plus">test galaxy s23 plus</div>
<div class="" id="galaxy-s23">test galaxy s23</div>
{% endblock content %}

templates/mysite/comment_form.html
{% extends '_base.html' %} {% block content %}
<h2>update comment</h2>
<section class="mb-5">
  <div class="card bg-light">
    <div class="card-body">
      <form method="post" class="mb-4" action="{% url 'comment_update' comment.id %}">
        {% csrf_token %}
        <textarea id="content" name="content" class="form-control" rows="3">{{ form.content.value }}</textarea>
        <button type="submit" class="btn btn-primary">submit</button>
      </form>
    </div>
  </div>
</section>
{% endblock %}

templates/mysite/content_detail.html
{% extends '_base.html' %} 
{% block content %}
<h2>{{ content_list.title }}</h2>
<div>{{ content_list.content }}</div>
<section class="mb-5">
  <div class="card bg-light">
    <div class="card-body">
      <form method="post" class="mb-4" action="{% url 'comment_create' content_list.id %}">
        {% csrf_token %}
        <textarea
          id="content"
          name="content"
          class="form-control"
          rows="3"
          placeholder="내용을 입력해주세요."
        ></textarea>
        <button type="submit" class="btn btn-primary">submit</button>
      </form>
      {% for comment in content_list.comment_set.all %}
      <div class="d-flex">
        <div class="ms-3">
          <div class="fw-bold">
            {{ comment.author.username }} &nbsp&nbsp {{ comment.create_date }}
            {% if comment.create_date != comment.modify_date %}
            / 수정일자: {{ comment.modify_date }}
            {% endif %}
            {% if request.user == comment.author %}
            <a href="{% url 'comment_update' comment.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="{% url 'comment_delete' comment.id %}" class="btn btn-sm btn-outline-secondary">삭제</a>
            {% endif %}
          </div>
          {{ comment.content }}
        </div>
      </div>
      <br />
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

templates/mysite/content_list.html
{% extends "../_base.html" %} {% block content %}

<h1>mysite</h1>
{% if content_list %} {% for content in content_list %}
<hr />
<h3><a href="/mysite/{{ content.id }}/">{{ content.title }}</a></h3>
<a
  class="btn btn-primary"
  href="
{% url 'detail' content.id %}
"
  >상품 상세보기</a
>
<h5>{{ content.content}}</h5>
{% endfor %} {% else %}
<p>content 가 없습니다.</p>
{% endif %} {% endblock content %}

templates/pages/company_info.html
{% extends "../_base.html" %} {% block content %}
<h1>회사소개 페이지입니다.</h1>
{% endblock content %}

templates/pages/mainpage.html
{% extends "../_base.html" %} {% block content %}
<h1>메인 페이지입니다.</h1>
{% endblock content %}

templates/shop/index.html
<!-- templates/home/index.html -->
{% extends "../_base.html" %} {% block content %}

<nav class="bg-gray-100 fixed w-full z-10 top-0 left-0">
  <div
    class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <span class="self-center text-2xl font-semibold whitespace-nowrap"
      >Galaxy S23</span
    >

    <div class="items-center justify-between hidden w-full md:flex w-auto">
      <ul class="flex flex-col p-4 md:p-0 mt-4 md:flex-row md:space-x-8 mt-0">
        <li>
          <a href="#" class="block py-2 pl-3 pr-4 text-black">현재가격</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="relative w-full h-full flex flex-row">
  <div class="relative w-2/3 h-screen sticky top-0 px-16 py-10">
    <div
      class="absolute inset-x-1/4 inset-y-1/4 flex mx-auto h-fit rounded-2xl bg-gray-100 justify-center items-center">
      <img
        class="block w-auto m-20"
        src="/static/image/shop/galaxy-s23-ultra-compare-green.webp" />
    </div>
  </div>
  <div class="">
    <div class="mt-80 mb-80">
      <div class="mb-4 text-gray-500 text-xl">
        <span class="font-semibold text-black">Model.</span>
        Which is best for you?
      </div>
      <div>
        <div class="flex rounded-lg border-2 border-blue-700 p-4 mt-4">
          <div class="grow">
            <div class="font-semibold">Galaxy S23</div>
            <div class="text-xs my-px">6.1-inch display</div>
          </div>
          <div class="text-xs text-right">
            From $699 <br />or $29.13/mo.<br />for 24mo.
          </div>
        </div>
        <div class="flex rounded-lg border border-gray-500 p-4 mt-4">
          <div class="grow">
            <div class="font-semibold">Galaxy S23 Plus</div>
            <div class="text-xs my-px">6.6-inch display</div>
          </div>
          <div class="text-xs text-right">
            From $919 <br />or $38.29/mo.<br />for 24mo.
          </div>
        </div>
        <div class="flex rounded-lg border border-gray-500 p-4 mt-4">
          <div class="grow">
            <div class="font-semibold">Galaxy S23 Ultra</div>
            <div class="text-xs my-px">6.9-inch display</div>
          </div>
          <div class="text-xs text-right">
            From $1199 <br />or $49.95/mo.<br />for 24mo.
          </div>
        </div>
      </div>
    </div>
    <div class="mb-80">
      <div class="mb-4 text-gray-500 text-xl">
        <span class="font-semibold text-black">Finish.</span>
        Pick your favorite.
      </div>

      <div>option</div>
    </div>
    <div class="mb-80">
      <div class="mb-4 text-gray-500 text-xl">
        <span class="font-semibold text-black">Storage.</span>
        How much space do you need?
      </div>
      <div>
        <div
          class="flex rounded-lg border border-gray-500 p-4 mt-4 items-center">
          <div class="grow">
            <div class="font-semibold">256GB</div>
          </div>
          <div class="text-xs text-right">
            From $1199 <br />or $49.95/mo.<br />for 24mo.
          </div>
        </div>
        <div
          class="flex rounded-lg border border-gray-500 p-4 mt-4 items-center">
          <div class="grow">
            <div class="font-semibold">512GB</div>
            <div class="text-xs text-amber-500">FREE UPGRADE</div>
          </div>
          <div class="text-xs text-right">
            From $1199 <br />or $49.95/mo.<br />for 24mo.
          </div>
        </div>
        <div
          class="flex rounded-lg border border-gray-500 p-4 mt-4 items-center">
          <div class="grow">
            <div class="font-semibold">1TB</div>
          </div>
          <div class="text-xs text-right">
            From $1619 <br />or $67.46/mo.<br />for 24mo.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div>추가내용설명</div>

{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>